### ISSUE TITLE
Bug - Event "on touch sensor" occurred twice

### ISSUE THREAD

**Issue by narongporn** [1010Technologies/pxt-makerbit-touch#3]
I try the latest version of this extension.
I use event "on touch sensor" to detect any key pressed.
I just pressed a key onec, but this event occurred twice.

**Comment by philipphenkel** [comment]
Ooops, we overlooked this issue. Would you please test again with latest MakeCode and extension. Event handling was much improved in MakeCode.
Please share your program, if the problem persists.

**Comment by narongporn** [comment]
The latest versionb is OK.
Thanks for creating this extension.
